BackDoctor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from account.urls import mobile_urlpatterns as account_mobile_url
from advertisement.urls import mobile_urlpatterns as advertisement_mobile_url
from schedule.urls import mobile_urlpatterns as schedule_mobile_url

mobile_urlpatterns = [
    url(r'^', include(account_mobile_url, namespace='account')),
    url(r'^schedule/', include(schedule_mobile_url, namespace='schedule')),
    url(r'^advertisement/', include(advertisement_mobile_url, namespace='advertisement')),
]

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(mobile_urlpatterns, namespace='api')),
    url(r'^', include('account.urls', namespace='account')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^advertisement/', include('advertisement.urls', namespace='advertisement')),
    url(r'^$', TemplateView.as_view(
        template_name='back-doctor/home-page.html'), name='home'),
]

account/urls.py
from django.conf.urls import url, include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from account.views.doctor_profile_views import DoctorProfileView, DoctorEditProfileView
from account.views.doctor_views import DoctorViews
from account.views.join_views import JoinView, JoinDoctorView
from account.views.login_views import LoginView, LogoutView
from account.views.profile_views import EditProfileView, UserProfileView
from account.views.user_views import UserViews

mobile_login_urlpatterns = [
    url(r'^$', obtain_jwt_token, name='login'),
    url(r'^refresh/$', refresh_jwt_token, name='refresh'),
    url(r'^verify/$', verify_jwt_token, name='verify')
]

mobile_urlpatterns = [
    url(r'^join/$', UserViews.as_view({'post': 'create'}), name='join'),
    url(r'^login/', include(mobile_login_urlpatterns, namespace='login')),
    url(r'^profile/$', UserViews.as_view({'get': 'retrieve', 'post': 'update'}), name='profile'),
    url(r'^search/(?P<q>[^w]+)/$', DoctorViews.as_view({'get': 'list'}), name='search'),
    url(r'^doctor/(?P<id>\d+)/$', DoctorViews.as_view({'get': 'retrieve'}), name='show-doctor'),
]

profile_urlpatterns = [
    url(r'^$', UserProfileView.as_view(), name='show'),
    url(r'^edit/$', EditProfileView.as_view(), name='edit')
]

doctor_profile_urlpatterns = [
    url(r'^$', DoctorProfileView.as_view(), name='show'),
    url(r'^edit/$', DoctorEditProfileView.as_view(), name='edit')
]

urlpatterns = [
    url(r'^join/$', JoinView.as_view(), name='join'),
    url(r'^join/doctor', JoinDoctorView.as_view(), name='join-doctor'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile/', include(profile_urlpatterns, namespace='profile')),
    url(r'^doctor-profile/', include(doctor_profile_urlpatterns, namespace='doctor-profile'))
]

schedule/urls.py
from django.conf.urls import url, include

from schedule.views.appointments_views import AppointmentsByDayView, AppointmentCancelView
from schedule.views.request_views import RequestShowAllView, RequestAcceptView, RequestRejectView
from schedule.views.schedule_views import DoctorScheduleView, DoctorAddScheduleView
from schedule.views.show_schedule_views import ScheduleViews
from schedule.views.slot_views import RequestSlotViews, ReservedSlotViews, FailedSlotViews

mobile_slots_urlpatterns = [
    url(r'^$', ScheduleViews.as_view({'get': 'days'}), name='days'),
    url(r'^(?P<day>[^w]+)$', ScheduleViews.as_view({'get': 'list'}), name='day'),
]

mobile_slot_urlpatterns = [
    url(r'^request/$', RequestSlotViews.as_view({'post': 'create'}), name='request'),
    url(r'^cancel-request/$', RequestSlotViews.as_view(
        {'post': 'destroy'}), name='cancel-request'),
    url(r'^cancel-reserve/$', ReservedSlotViews.as_view(
        {'post': 'destroy'}), name='cancel-reserve'),
]

mobile_urlpatterns = [
    url(r'^slots/(?P<schedule>\d+)/', include(mobile_slots_urlpatterns, namespace='slots')),
    url(r'^(?P<slot>\d+)/', include(mobile_slot_urlpatterns, namespace='slot')),
    url(r'^requests/$', RequestSlotViews.as_view({'get': 'list'}), name='requests'),
    url(r'^reserves/$', ReservedSlotViews.as_view({'get': 'list'}), name='reserves'),
    url(r'^failed-requests/$', FailedSlotViews.as_view({'get': 'list'}), name='failed-requests'),
]

request_urlpatterns = [
    url(r'^show-all/$', RequestShowAllView.as_view(), name='show_all'),
    url(r'^(?P<id>\d+)/accept/$', RequestAcceptView.as_view(), name='accept'),
    url(r'^(?P<id>\d+)/reject/$', RequestRejectView.as_view(), name='reject'),
]

appointments_urlpatterns = [
    url(r'^$', AppointmentsByDayView.as_view(), name='show_all'),
    url(r'^(?P<year>\d+)?/(?P<month>\d+)?/(?P<day>\d+)?/$',
        AppointmentsByDayView.as_view(), name='filter'),
    url(r'^(?P<id>\d+)/cancel/$', AppointmentCancelView.as_view(), name='cancel'),
]

urlpatterns = [
    url(r'^show/$', DoctorScheduleView.as_view(), name='show'),
    url(r'^add/$', DoctorAddScheduleView.as_view(), name='add'),
    url(r'^request/', include(request_urlpatterns, namespace='request')),
    url(r'^appointments/', include(appointments_urlpatterns, namespace='appointments')),
]

schedule/models.py
from datetime import timedelta

from dateutil.parser import parse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch.dispatcher import receiver

DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"


class Schedule(models.Model):
    doctor = models.OneToOneField('account.Doctor', related_name='schedule')
    visit_time = models.IntegerField(default=15)

    @property
    def request_numbers(self):
        return ScheduleSlotRequest.objects.filter(slot__schedule=self).count()

    @staticmethod
    def check_slots_availability(day, start_time, finish_time):
        start_times = ScheduleSlot.objects.filter(
            day=day, start_time__gte=start_time, start_time__lt=finish_time)
        finish_times = ScheduleSlot.objects.filter(
            day=day, finish_time__gt=start_time, finish_time__lte=finish_time)
        if start_times.exists() or finish_times.exists():
            raise ValidationError('You already set work time in this range!')

    def create_slots(self, day, start_time, finish_time):
        self.check_slots_availability(day, start_time, finish_time)
        day = parse(day)
        start_time = parse(start_time)
        start_time = timedelta(hours=start_time.hour, minutes=start_time.minute)
        finish_time = parse(finish_time)
        finish_time = timedelta(hours=finish_time.hour, minutes=finish_time.minute)
        while start_time < finish_time:
            next_time = start_time + timedelta(minutes=self.visit_time)
            ScheduleSlot.objects.create(
                schedule=self, day=day, start_time=str(start_time), finish_time=str(next_time))
            start_time = next_time

    def __str__(self):
        return '%s' % self.doctor


class ScheduleSlot(models.Model):
    schedule = models.ForeignKey('Schedule', related_name='slots')
    day = models.DateField()
    start_time = models.TimeField()
    finish_time = models.TimeField()

    class Meta:
        unique_together = ('schedule', 'day', 'start_time')

    @property
    def patient(self):
        return self.reserve.patient if hasattr(self, 'reserve') else None

    @property
    def is_reserved(self):
        return True if self.patient else False

    def __str__(self):
        return '%s - %s : %s - %s' % (
            self.schedule.doctor,
            self.day.strftime("%s" % (DATE_FORMAT,)),
            self.start_time.strftime("%s" % (TIME_FORMAT,)),
            self.finish_time.strftime("%s" % (TIME_FORMAT,)),
        )


class ScheduleSlotReserved(models.Model):
    created = models.DateTimeField(auto_now_add=True, unique=True)
    patient = models.ForeignKey(User, related_name='reserves')
    slot = models.OneToOneField('ScheduleSlot', related_name='reserve')

    def cancel(self, user):
        if user == self.slot.schedule.doctor.member.user:
            ScheduleSlotFailedReserve.objects.create(
                patient=self.patient,
                doctor=self.slot.schedule.doctor,
                day=self.slot.day,
                start_time=self.slot.start_time,
                finish_time=self.slot.finish_time
            )
            self.delete()


class ScheduleSlotRequest(models.Model):
    created = models.DateTimeField(auto_now_add=True, unique=True)
    patient = models.ForeignKey(User, related_name='reserve_requests')
    slot = models.ForeignKey('ScheduleSlot', related_name='reserve_requests')

    def __init__(self, *args, **kwargs):
        super(ScheduleSlotRequest, self).__init__(*args, **kwargs)
        self._must_delete = True

    def accept(self, user):
        if user == self.slot.schedule.doctor.member.user:
            self._must_delete = False
            self.delete()
            ScheduleSlotReserved.objects.create(
                patient=self.patient,
                slot=self.slot
            )

    def reject(self, user):
        if user == self.slot.schedule.doctor.member.user:
            ScheduleSlotFailedReserve.objects.create(
                patient=self.patient,
                doctor=self.slot.schedule.doctor,
                day=self.slot.day,
                start_time=self.slot.start_time,
                finish_time=self.slot.finish_time
            )
            self.delete()


class ScheduleSlotFailedReserve(models.Model):
    created = models.DateTimeField(auto_now_add=True, unique=True)
    patient = models.ForeignKey(User, related_name='reserve_fails')
    doctor = models.ForeignKey('account.Doctor', related_name='+')
    day = models.DateField()
    start_time = models.TimeField()
    finish_time = models.TimeField()


@receiver(post_save, sender=ScheduleSlotReserved)
def update_failed_reserves_on_reserved(instance, **kwargs):
    ScheduleSlotRequest.objects.filter(slot=instance.slot).delete()


@receiver(post_delete)
def update_failed_reserves_on_delete(sender, instance, **kwargs):
    list_of_models = ['ScheduleSlotRequest', 'ScheduleSlotReserved']
    if sender.__name__ in list_of_models:
        if getattr(instance, '_must_delete', True):
            ScheduleSlotFailedReserve.objects.create(
                patient=instance.patient,
                doctor=instance.slot.schedule.doctor,
                day=instance.slot.day,
                start_time=instance.slot.start_time,
                finish_time=instance.slot.finish_time,
            )

advertisement/forms/doctor_upgrade_forms.py
import datetime

from django import forms
from django.forms.models import ModelForm

from account.models import Doctor


class DoctorUpgradeForm(ModelForm):
    year = forms.IntegerField(min_value=datetime.datetime.now().year)
    month = forms.IntegerField(max_value=12, min_value=1)

    class Meta:
        model = Doctor
        fields = ('year', 'month')

    def __init__(self, *args, **kwargs):
        super(DoctorUpgradeForm, self).__init__(*args, **kwargs)
        self.doctor = None

    def save(self, commit=True):
        data = self.cleaned_data
        self.doctor.promote(str(data['year']) + '-' + str(data['month']) + '-01')
        return self.doctor

schedule/forms/schedule_forms.py
from django.forms.models import ModelForm

from schedule.models import ScheduleSlot


class AddScheduleForm(ModelForm):
    class Meta:
        model = ScheduleSlot
        fields = ('day', 'start_time', 'finish_time')
        labels = {'start_time': 'Start Time', 'finish_time': 'Finish Time'}

    def __init__(self, *args, **kwargs):
        super(AddScheduleForm, self).__init__(*args, **kwargs)
        self.schedule = None

    def save(self, commit=True):
        data = self.cleaned_data
        self.schedule.create_slots(
            str(data['day']), str(data['start_time']), str(data['finish_time']))
        return self.schedule

schedule/views/appointments_views.py
from django.shortcuts import redirect
from django.urls.base import reverse
from django.views.generic.base import View
from django.views.generic.list import ListView

from schedule.models import ScheduleSlotReserved


class AppointmentsByDayView(ListView):
    model = ScheduleSlotReserved
    template_name = 'schedule/show-appointments.html'

    def get_queryset(self):
        filter_args = {'slot__schedule__doctor__member__user': self.request.user}
        for key in self.kwargs:
            if self.kwargs[key]:
                filter_args['slot__day__' + key] = self.kwargs[key]
        queryset = ScheduleSlotReserved.objects.filter(**filter_args)
        return queryset.order_by('-created')


class AppointmentCancelView(View):
    def get(self, request, **kwargs):
        try:
            slot_reserved = ScheduleSlotReserved.objects.get(id=kwargs.get('id', None))
            slot_reserved.cancel(request.user)
        except Exception as e:
            print(e)
        return redirect(reverse('schedule:appointments:show_all'))

schedule/views/request_views.py
from django.shortcuts import redirect
from django.urls.base import reverse
from django.views.generic.base import View
from django.views.generic.list import ListView

from schedule.models import ScheduleSlotRequest


class RequestShowAllView(ListView):
    model = ScheduleSlotRequest
    template_name = 'schedule/show-requests.html'

    def get_queryset(self):
        return ScheduleSlotRequest.objects.filter(
            slot__schedule__doctor__member__user=self.request.user).order_by('-created')


class RequestAcceptView(View):
    def get(self, request, **kwargs):
        try:
            slot_request = ScheduleSlotRequest.objects.get(id=kwargs.get('id', None))
            slot_request.accept(request.user)
        except Exception as e:
            print(e)
        return redirect(reverse('schedule:request:show_all'))


class RequestRejectView(View):
    def get(self, request, **kwargs):
        try:
            slot_request = ScheduleSlotRequest.objects.get(id=kwargs.get('id', None))
            slot_request.reject(request.user)
        except Exception as e:
            print(e)
        return redirect(reverse('schedule:request:show_all'))

schedule/views/schedule_views.py
from django.shortcuts import render
from django.urls.base import reverse
from django.views.generic.base import View
from django.views.generic.edit import CreateView

from schedule.forms.schedule_forms import AddScheduleForm
from schedule.models import ScheduleSlot


class DoctorScheduleView(View):
    @staticmethod
    def get(request):
        user = request.user
        doctor = user.member.doctor
        schedule = doctor.schedule
        data = [
            {'label': 'Visit Time', 'data': schedule.visit_time},
            {'label': 'Schedule Work Days', 'data': schedule.slots.all()},
        ]
        return render(request, 'schedule/show-schedule.html', {'data': data})


class DoctorAddScheduleView(CreateView):
    model = ScheduleSlot
    template_name = 'schedule/add-schedule.html'
    form_class = AddScheduleForm

    def get_form(self, form_class=None):
        form = super(DoctorAddScheduleView, self).get_form(form_class)
        form.schedule = self.request.user.member.doctor.schedule
        return form

    def get_success_url(self):
        return reverse('schedule:show')

schedule/views/show_schedule_views.py
from datetime import date

from django.http.response import Http404
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from schedule.models import Schedule
from schedule.serializers.schedule_serializers import ScheduleSlotSerializer
from schedule.utils import ScheduleSlotSetPagination
from utils.base_rest_views import BaseRestViews


class ScheduleViews(BaseRestViews):
    pagination_class = ScheduleSlotSetPagination
    serializer_class = ScheduleSlotSerializer
    lookup_fields = {
        'days': ('schedule',),
        'list': ('schedule', 'day')
    }
    http_method_names = ['get']
    permission_classes = {
        'days': [IsAuthenticated],
        'list': [IsAuthenticated],
    }

    def __init__(self, **kwargs):
        self.schedule = None
        self.day = None
        self.slots = None
        super(ScheduleViews, self).__init__(**kwargs)

    def initial(self, request, *args, **kwargs):
        self.schedule = kwargs.get('schedule', None)
        if self.schedule:
            self.schedule = get_object_or_404(Schedule, pk=self.schedule)
        self.day = kwargs.get('day', None)
        if self.day and self.schedule:
            try:
                self.slots = self.schedule.slots.filter(day=self.day)
            except Exception:
                raise Http404
        return super(ScheduleViews, self).initial(request, *args, **kwargs)

    def get_queryset(self):
        return self.slots

    def days(self, request, *args, **kwargs):
        days = self.schedule.slots \
            .filter(day__gte=date.today().strftime("%Y-%m-%d")) \
            .order_by('day') \
            .values_list('day', flat=True) \
            .distinct()
        return Response(days)

schedule/templates/schedule/add-schedule.html
{% extends "back-doctor/base.html" %}
{% load i18n %}

{% block title %}{% trans "Add day" %}{% endblock title %}

{% block content %}
<div class="mdl-grid content">
    <div class="login-panel input-list mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col">
        <form action="" method="post">
            {% csrf_token %}
            <ul class="mdl-list">
                <li class="mdl-list__item">
                    {% if form.errors %}
                    <p class="mdl-color-text--accent">
                        {% trans "Please add correct times" %}
                    </p>
                    {% endif %}
                </li>
                <li class="mdl-list__item">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        {{ form.day.label_tag }}
                        {{ form.day }}
                    </div>
                </li>
                <li class="mdl-list__item">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        {{ form.start_time.label_tag }}
                        {{ form.start_time }}
                    </div>
                </li>
                <li class="mdl-list__item">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        {{ form.finish_time.label_tag }}
                        {{ form.finish_time }}
                    </div>
                </li>
                <li class="mdl-list__item">
                    <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent">
                        {% trans "Add" %}
                    </button>
                </li>
            </ul>
        </form>
    </div>
</div>
{% endblock content %}

schedule/templates/schedule/show-appointments.html
{% extends "back-doctor/base.html" %}
{% load i18n %}

{% block title %}{% trans "Show Appointments" %}{% endblock title %}

{% block content %}
<div class="mdl-grid content">
    <div class="datefilter input-list mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col">
        <ul class="mdl-list">
            <li class="mdl-list__item">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <label for="id_year">Year:</label>
                        <input id="id_year" name="year" type="text"/>
                </div>
            </li>
            <li class="mdl-list__item">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <label for="id_month">Month:</label>
                        <input id="id_month" name="month" type="text"/>
                </div>
            </li>
            <li class="mdl-list__item">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <label for="id_day">Day:</label>
                        <input id="id_day" name="day" type="text"/>
                </div>
            </li>
            <li class="mdl-list__item">
                <a href="{% url 'schedule:appointments:show_all' %}" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent">
                    {% trans "Filter" %}
                </a>
            </li>
        </ul>

        <script>
            var base = $('.datefilter a').attr('href');
            $('.datefilter input').change(function() {
                var year = $('.datefilter [name=year]').val();
                var month = $('.datefilter [name=month]').val();
                var day = $('.datefilter [name=day]').val();
                var params = year + '/' + month + '/' + day + '/';
                $('.datefilter a').attr('href', base + params);
            });
        </script>
    </div>
        <table class="mdl-data-table mdl-js-data-table mdl-data-table mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col">
            <thead>
            <tr>
                <th class="mdl-data-table__cell--non-numeric">{% trans "User" %}</th>
                <th class="mdl-data-table__cell--non-numeric">{% trans "Visit Date" %}</th>
                <th class="mdl-data-table__cell--non-numeric">{% trans "Visit Start" %}</th>
                <th class="mdl-data-table__cell--non-numeric">{% trans "Visit End" %}</th>
                <th class="mdl-data-table__cell--non-numeric">{% trans "Requested at" %}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for request in object_list %}
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">{{ request.patient.username }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ request.slot.day }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ request.slot.start_time }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ request.slot.finish_time }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ request.created }}</td>
                    <td class="mdl-data-table__cell--non-numeric">
                        <form action="{% url 'schedule:appointments:cancel' id=request.id %}">
                            <input type="submit" value="Cancel" class=
                                    "mdl-button mdl-js-button mdl-button--raised
                                    mdl-color-text--grey-200 mdl-color--red-600">
                            </input>
                        </form>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>


    </div>
</div>

{% endblock content %}

schedule/templates/schedule/show-requests.html
{% extends "back-doctor/base.html" %}
{% load i18n %}

{% block title %}{% trans "Show Requests" %}{% endblock title %}

{% block content %}


    <div class="mdl-grid content">

            <table class="mdl-data-table mdl-js-data-table mdl-data-table mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col">
                <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric">{% trans "User" %}</th>
                    <th class="mdl-data-table__cell--non-numeric">{% trans "Visit Date" %}</th>
                    <th class="mdl-data-table__cell--non-numeric">{% trans "Visit Start" %}</th>
                    <th class="mdl-data-table__cell--non-numeric">{% trans "Visit End" %}</th>
                    <th class="mdl-data-table__cell--non-numeric">{% trans "Requested at" %}</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for request in object_list %}
                    <tr>
                        <td class="mdl-data-table__cell--non-numeric">{{ request.patient.username }}</td>
                        <td class="mdl-data-table__cell--non-numeric">{{ request.slot.day }}</td>
                        <td class="mdl-data-table__cell--non-numeric">{{ request.slot.start_time }}</td>
                        <td class="mdl-data-table__cell--non-numeric">{{ request.slot.finish_time }}</td>
                        <td class="mdl-data-table__cell--non-numeric">{{ request.created }}</td>
                        <td class="mdl-data-table__cell--non-numeric">
                            <form action="{% url 'schedule:request:accept' id=request.id %}">
                                <input type="submit" value="Accept" class=
                                        "mdl-button mdl-js-button mdl-button--raised
                                        mdl-color-text--grey-200 mdl-color--green-600">
                                </input>
                            </form>
                        </td>
                        <td class="mdl-data-table__cell--non-numeric">
                            <form action="{% url 'schedule:request:reject' id=request.id %}">
                                <input type="submit" value="Reject" class=
                                        "mdl-button mdl-js-button mdl-button--raised
                                        mdl-color-text--grey-200 mdl-color--red-600">
                                </input>
                            </form>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>

    </div>

{% endblock content %}

schedule/templates/schedule/show-schedule.html
{% extends "back-doctor/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Schedule / Available Times" %}{% endblock title %}

{% block content %}
<div class="mdl-grid content">
    <div class="profile-panel mdl-card mdl-shadow--2dp mdl-cell mdl-cell--8-col">
        <form action="{% url 'schedule:add' %}" method="get" autocomplete="off">
            <ul class="mdl-list">
                <li class="mdl-list__item">
                    <label> {% trans "Visit time" %}: </label>
                    <span>{{ data.0.data}}</span>
                </li>
                <li class="mdl-list__item">
                    <label> {% trans "Available times" %}: </label>
                </li>
                {% for day in data.1.data %}
                <li class="mdl-list__item">
                    <span>{{ day.day }} - {{ day.start_time }} - {{ day.finish_time }}</span>
                </li>
                {% endfor %}
                <li class="mdl-list__item">
                    <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent">
                        {% trans "Add available time" %}
                    </button>
                </li>
            </ul>
        </form>
    </div>
</div>
{% endblock content %}